version: '3.9'

services:
  web:
    build: .
    command: python /Agro1/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Agro1
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-=8rb8u@5blzi=d#xwt4asuke#r+yq%)*c%u)5gizt%h8o8(yj4"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
  postgres_data: